//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Information = new HashSet<Information>();
            this.Modify = new HashSet<Modify>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int status { get; set; }
    
        public virtual ICollection<Information> Information { get; set; }
        public virtual ICollection<Modify> Modify { get; set; }
    }
}
